packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - canvas
  - esbuild
  - prisma

onlyBuiltDependencies:
  - citation-js
  - core-js
  - electron
  - sharp
