name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: |
          cd apps/frontend
          pnpm build
          cd ../..

      - name: Zip frontend build
        run: |
          cd apps/frontend/dist
          zip -r ../../frontend-dist.zip .
          cd ../..

      - name: Zip backend source
        run: |
          cd apps/backend
          zip -r ../../backend-src.zip src prisma package.json tsconfig.json
          cd ../..

      - name: Generate Release Notes
        id: changelog
        run: |
          echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
          awk '/^## \[/{if (p) exit; p=1; next} p' CHANGELOG.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.RELEASE_NOTES }}
          files: |
            frontend-dist.zip
            backend-src.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 